// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type CollectedChapter struct {
	Releasetitle  string
	Releaselink   string
	Mangatitle    string
	Chapternumber string
	Chaptertitle  string
	Releasetime   string
}
